require:
  - rubocop-rspec

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NumberedParametersLimit:
  Max: 2

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 27

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 15

Gemspec/RequireMFA:
  Enabled: false
